language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: vLkv1WkoaP9QCu/qI4PfcvpxZs/IvFBjl2XSQ+TP450nVUW6Bq+GpfE3YqvbDGc0TXdcbojo5PsggK+udR0xtMN5zDRH19yklqCXEvaXqg2o/fz3e1BFVqSMYMOdnqZbRaawTkik9C8wtUb5EQLlkXIVBHf6HqB/Oy9Zr3H3CMTCEUWf01KtGnnTLUuE/hGL3pLEq4j6HOcySxW/8TGyncbI9qlV4IL/UWEyMMD6iqCeZ0wl8KKo3HwBuSYJvxZJWSEx3EHo6CZh8c4juoheuToHXqRdOPJX/fchsORE5wkVmWewJG+cXo/mPDCxQcopYN0SD+HF9EFK0aCOZoL40PiWdZl3v/XGRICOglZZQTkHo0g2+nbSzccwqv+lXRm7QsM2g4Q6O1/hEtEdGiKK6dK3kXhE43FmzzGA3cWKuWyF1sX/hUtavwRgDFl2rvuCicoZ1LEx2DNGsnHYkhjp+M1xaaEzMM+jLcm2/ijSFEtixPTCeSFVjBEhSKmi4uJhMSXVf64wMslc52ixs1WlT1phjV1ZAd4WIDoihleQTcgex1M7vJtoJHjeYFuULbmom+xQ4tnlB8JbYlPJFW3V8k2+7o/qtkN+9iMSxrsptR8U3g36fl7ePljtt7Mjl+cDbQPGxSUSswCDvY26LzrjjqWdAQ717anPdjJ8Wyvm7pw=
  on:
    tags: true
    branches: true
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- bash <(curl -s https://codecov.io/bash)
